name: CI

on:
  push:
    branches:
      - main

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Run test
        run: cd Klient/Tests && dotnet test
        env:
          pgconn: ${{secrets.PGCONN}}